### ISSUE TITLE
Migrate ‘web’ directory from ‘Revolutionary_Farmers’ to ‘Revo-Frontend’ preserving commit history

### ISSUE THREAD

**Issue by sasasamaes** [Crypto-Jaguars/Revo-Frontend#12]
The goal is to extract the frontend component from our existing monorepo and migrate it to the newly created revo-frontend repository while preserving the entire git history specific to the frontend directory. We will use git subtree split to create a clean extraction of the frontend codebase, ensuring all commit history, branches, and relevant metadata are transferred accurately. This migration will improve our project's modularity, allow independent versioning of the frontend, and potentially simplify our development workflow by providing a dedicated repository for frontend-specific tasks and contributions.

See more details here:
https://docs.github.com/es/get-started/using-git/splitting-a-subfolder-out-into-a-new-repository

**Comment by salazarsebas** [comment]
PR merged
