### ISSUE TITLE
[bug] Update the general documentation of this repository

### ISSUE THREAD

**Issue by salazarsebas** [Crypto-Jaguars/Revo-Frontend#27]
### Steps to Reproduce

Detect bugs contained in the current readme. Change incorrect routes. Add a couple of emojis to improve the aesthetics.

### Actual Behavior

Currently the readme contains errors because it was migrated from the old repo.
The old repo contained the web folder and this repo consists of that old web folder, therefore in the addresses you have to remove “web” in the commands or addresses.

### Expected Behavior

An updated readme is expected, where the steps required to work with this repository are clearly understood.
The issue is to update the readme.

### Severity of the Issue

Low

**Comment by 0xdevcollins** [comment]
Can I be assigned this issue?

**Comment by johnnyzaet08** [comment]
Hey mate ⛩⛩, could I be assigned to this?
I have experience in TypeScript and projects like this, so I can help to solve the problems and make it more aesthetic. My ETA for this issue is 10h

**Comment by 3th-Enjay** [comment]
Can I try solving this issue?

**Comment by sonkeydotcom** [comment]
Mind if I try this one?

**Comment by ryzen-xp** [comment]
Let me handle this issue!

**Comment by pablomadrigal** [comment]
## I'm Pablo Madrigal.

I'm a Fullstack Developer with more than 5 years of experience primarily on React and Node.js and now learning web3, I'm also part of Dojo Coding ⛩️

## Problem

Update the general documentation of this repository

## Solution

I'm going to fix the readme to be specific to the migrated repository and instructions to run the project locally

**Comment by Kingsuite** [comment]
May I take this issue on? I've worked on several documentation related issues

**Comment by greatest0fallt1me** [comment]
Mind if I take this issue?

**Comment by salazarsebas** [comment]
Issue assigned @greatest0fallt1me , good luck. 🫡
If you have any questions we are at your disposal and you can also join our telegram channel. 📨👨🏻‍💻

**Comment by salazarsebas** [comment]
PR merged
