### ISSUE TITLE
Fix the flow by connecting the wallet by changing the language in between and disconnecting the wallet.

### ISSUE THREAD

**Issue by salazarsebas** [Crypto-Jaguars/Revo-Frontend#3]
### 🔍 Description
- We need manual testing to be performed to the web application regarding the wallet connection and disconnection in combination with the use of the language switch button. Based on the results obtained you should fix the bugs found after the tests.

### 🔄 Steps to Reproduce:
1. Perform manual tests.
2. List the bugs in the specified functions.
3. Solve the bugs found.
(It is recommended to have communication in the telegram group, or with the mainteiners).

### ✅ Expected Behavior:
- An excellent functioning of the flow described above (Wallet + Language switch button).

###  📸 Screenshots:

<img width="1399" alt="Image of what the issue to be solved looks like" src="https://github.com/user-attachments/assets/1bb481bf-3a51-4a47-81f1-f685bf050838" />

These screens where no information is displayed are the ones we want to fix.

This video shows the bug described above:

https://github.com/user-attachments/assets/51b0925b-0359-42ae-9ffb-124582bfe27c

We will be very happy to see your applications, good luck!

Announcement: This issue does not contain reward.

**Comment by ShantelPeters** [comment]
Could I take a shot at this?

**Comment by Jagadeeshftw** [comment]
Hi, I’d love to work on this issue as I have strong experience with both Stellar and Rust. I’ve developed secure and efficient smart contracts, blockchain integrations, and high-performance backend systems. Please assign this to me, and I’ll ensure to deliver a robust and high-quality PR within 12-24 hours.

**Comment by Michaelkingsdev** [comment]
I’d love to work on this task.

**Comment by Benjtalkshow** [comment]
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 49 contributions to over 17 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

I can handle this task.
ETA is 3days.
