### ISSUE TITLE
Fixes text

### ISSUE THREAD

**Issue by salazarsebas** [Crypto-Jaguars/Revo-Frontend#4]
### 🔍 Description
- Fixes text on the main page. It should not delete text, nor should it change words. This issue consists of removing “+” in some line breaks.

### 🔄 Steps to Reproduce:
1. Examine the main page looking for those digits that are not visible to the naked eye.
2. Remove what is not necessary, without changing the page layout.
3. Verify that everything is working the same and now more beautiful.

### ✅ Expected Behavior:
- It is expected that the main page does not contain the plus symbols. Nor any other unnecessary symbols.
In case you find other symbols please communicate it to the mainteiners.

###  📸Screenshots/Logs:

<img width="1399" alt="Image showing the plus symbols" src="https://github.com/user-attachments/assets/e49a3d38-5b20-4560-8335-e1441a06b3cd" />

We will be very happy to see your applications, good luck!

Announcement: This issue does not contain reward.

**Comment by ShantelPeters** [comment]
I’m interested in this one.

**Comment by ryzen-xp** [comment]
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity  and also in web development.
I have  contributed many cairo ,rust  projects like chainevents , arkprojects sunshine etc  .   please /assign  this issue .
Thank You

**Comment by Jagadeeshftw** [comment]
Hi, I’d love to work on this issue as I have strong experience with both Stellar and Rust. I’ve developed secure and efficient smart contracts, blockchain integrations, and high-performance backend systems. Please assign this to me, and I’ll ensure to deliver a robust and high-quality PR within 12-24 hours.

**Comment by Michaelkingsdev** [comment]
Could I take over this issue?

**Comment by Benjtalkshow** [comment]
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 49 contributions to over 17 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

I can handle this task.
ETA is 3days.

**Comment by Kom02** [comment]
Hi, I’m Kevin Obando, a full-stack software developer with 2 years of experience. Currently, I’m exploring the world of blockchain and am eager to gain hands-on experience in this field.

**Comment by DuendexCR** [comment]
Can I work on this, please?

**Comment by kimcascante** [comment]
I'm Kimberly Cascante, a proud member of Dojo Coding! ⛩️
I have previously worked with TypeScript, to disable buttons based on specific criteria. I'm passionate about design and frontend development and excited to contribute to this project.
My plan is to start by reviewing the code and page to identify what is not necessary and proceed to remove it. I'll test the changes, and prepare a PR for review.
Happy to contribute!
