### ISSUE TITLE
Place the logo on the tab

### ISSUE THREAD

**Issue by salazarsebas** [Crypto-Jaguars/Revo-Frontend#5]
### 🔍 Description
- The same logo that is already on the main page, place it on the tab. By tab we mean the logo that appears where you see the tabs, currently the previous logo is displayed. Basically what we need to do is to update it.

### 🔄 Steps to Reproduce:
1. Place the logo on the tab.

### ✅ Expected Behavior:
- We hope that the logo can be displayed correctly on the tab.

###  📸Screenshots/Logs:

This is the correct logo:

<img width="177" alt="Image with the correct logo" src="https://github.com/user-attachments/assets/8b4f69aa-7a48-4e94-b553-5b808ea70dd9" />

This is how it looks at the moment:

<img width="389" alt="Image of what it looks like before the issue was resolved" src="https://github.com/user-attachments/assets/b1ffa076-f0fc-40b3-a659-09d9c5fa23c2" />

We will be very happy to see your applications, good luck!

Announcement: This issue does not contain reward.

**Comment by CoderPrime99** [comment]
Hi! I'm Carlos, a Software Developer with over 2 years of experience. I've worked with C++, Java, and JavaScript, and I'm excited to make my first contribution to OnlyDust. It would be great to contribute to the project's sucess, I am also part of Dojo Coding.

I would update the favicon of the website by replacing the current logo with the one used on the main page. I would locate the favicon.ico file in the project, replace it with the correct logo file, and ensure it appears properly in the tab across all browsers. Afterward, I’d test the website to verify the logo is displayed correctly.

**Comment by therealemino** [comment]
Hi, I believe this is an excellent first issue for me to contribute to. Can take on this task?

**Comment by ShantelPeters** [comment]
Can I handle this task?

**Comment by akintola4** [comment]
i can do this , and i think i would be a good fit for this issue

**Comment by ryzen-xp** [comment]
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity  and also in web development.
I have  contributed many cairo ,rust  projects like chainevents , arkprojects sunshine etc  .   please /assign  this issue .
Thank You

**Comment by Jagadeeshftw** [comment]
Hi, I’d love to work on this issue as I have strong experience with both Stellar and Rust. I’ve developed secure and efficient smart contracts, blockchain integrations, and high-performance backend systems. Please assign this to me, and I’ll ensure to deliver a robust and high-quality PR within 12-24 hours.

**Comment by Michaelkingsdev** [comment]
Let me try this one!

**Comment by Benjtalkshow** [comment]
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 49 contributions to over 17 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

I can handle this task.
ETA is 3days.

**Comment by Baronvil** [comment]
Could I try solving this?

**Comment by Jethrolopwus** [comment]
Hi, I'm a front end developer with over 3years experience working with javascript, react.js, next.js and typescript. I will implement this with an ETA of 1hr max if assigned this issue.

**Comment by Kom02** [comment]
Hi, I’m Kevin Obando, a full-stack software developer with 2 years of experience. Currently, I’m exploring the world of blockchain and am eager to gain hands-on experience in this field.

**Comment by DuendexCR** [comment]
Can I take care of this issue?

**Comment by kimcascante** [comment]
I'm Kimberly Cascante, a proud member of Dojo Coding! ⛩️
I have previously worked with TypeScript, to disable buttons based on specific criteria. I'm passionate about design and frontend development and excited to contribute to this project.
My plan is to start by reviewing the logo in the main page then update it to the visible on tab. I'll test the changes, and prepare a PR for review.
Happy to contribute!

**Comment by ManuelJG1999** [comment]
Hi @Baronvil 

We hope you're doing well.
We wanted to check in on the progress of this task, as we've been trying to reach you. If we don't hear back by Sunday, we may need to reassign this issue to another contributor. Please let us know if there are any updates or if you need assistance. Thank you!

**Comment by ManuelJG1999** [comment]
@Baronvil 
Please, join our telegram chat for a faster communication 
https://t.me/Revolutionary_Farmers/1

Thank you.

**Comment by salazarsebas** [comment]
Hi @Baronvil , 
You have about 5 hours and 10 minutes to send your pr, good luck. 🌾

**Comment by ManuelJG1999** [comment]
removing assignment as no action was taken to address this issue.
