### ISSUE TITLE
Create dark mode and light mode button

### ISSUE THREAD

**Issue by salazarsebas** [Crypto-Jaguars/Revo-Frontend#7]
## Description
Remove the user icon (Between the connect wallet button and the change language button, see attached image). And in that place where the previous icon was, place a light and dark mode button.

And make the functionality of the button, the dark mode will be the style that currently has and the light mode will be a white background.

<img width="57" alt="Icon" src="https://github.com/user-attachments/assets/52a40a4f-93bd-43ab-b9b3-f2973031d365" />

**Comment by CristopherAguilar10** [comment]
Hi, I am interested in working on this issue. I have experience as a fullstack developer, with skills in technologies such as Java, C#, Python, JavaScript, React and more. I am currently part of Dojo Coding and I am lead of the Citizen of Arcanis project.

To address this issue, I plan to follow a structured approach to ensure a modular and functional implementation:

Remove the user icon, adjusting the layout to maintain visual consistency of the interface.
Add the light/dark mode toggle button where indicated.
Implement the functionality of the button, using CSS classes or style variables to handle the changes between both modes.
Perform visual and functional testing to ensure a smooth transition between themes and a good user experience.
I am open to feedback, especially in terms of design or integration with existing styles. If there are additional specifications or design details to consider, I would appreciate hearing from you. I estimate to be able to complete this issue in 1-2 days

**Comment by CoderPrime99** [comment]
Hi! I'm Carlos, a Software Developer with over 2 years of experience. I've worked with C++, Java, and JavaScript, and I'm excited to make my first contribution to OnlyDust. It would be great to contribute to the project's sucess, I am also part of Dojo Coding.

I would remove the user icon and add a button between the connect wallet and change language buttons to toggle dark and light modes. I’d implement a theme context to manage the theme state and apply a white background for light mode while keeping the current styles for dark mode. I’d ensure the theme choice is saved in localStorage and test the button for smooth switching and responsiveness across the site.

**Comment by markdavid000** [comment]
## About Me
I’m a blockchain and frontend developer passionate about creating decentralized applications. I have hands-on experience developing smart contracts on EVM-compatible blockchains using Solidity. I focus on building secure and efficient systems while crafting intuitive user interfaces to bridge the gap between complex blockchain technology and everyday users.

## Solution Plan
- I will write the code to create a dark and light mode toggle button and make it functional when clicked.
- I will maintain the brand color theme and project structure
- I will follow and maintain the codebase structure
- I will ensure the button is responsive and works across all devices
- I will test and make sure everything works accordingly before committing and making PR

## ETA
5 Hours

**Comment by mimisavage** [comment]
I’d like to help with this.

**Comment by ShantelPeters** [comment]
Is it okay if I take this?

**Comment by ryzen-xp** [comment]
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity  and also in web development.
I have  contributed many cairo ,rust  projects like chainevents , arkprojects sunshine etc  .   please /assign  this issue .
Thank You

**Comment by Jagadeeshftw** [comment]
Hi, I’d love to work on this issue as I have strong experience with both Stellar and Rust. I’ve developed secure and efficient smart contracts, blockchain integrations, and high-performance backend systems. Please assign this to me, and I’ll ensure to deliver a robust and high-quality PR within 12-24 hours.

**Comment by Kaminar-i** [comment]
Please can I work on this?

**Comment by SimplementeCao** [comment]
Hi, I'm Leandro, Front-end developer.
I would solve the issue first reviewing the code, removing the icon indicated and placing the button to change the theme, implement the functionality for the button.
Estimated delivery time: 24 hours.

I have previously collaborated in other projects such as:

Cairo Book
Starknet Book
Starknet Docs
Starknet Security Challenges Factory
Starkane
Can I work on this topic?

Check out my OnlyDust, I contributed to many projects: OnlyDust profile
and my GitHub

**Comment by Michaelkingsdev** [comment]
Can I take care of this issue?

**Comment by Benjtalkshow** [comment]
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 49 contributions to over 17 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

I can handle this task.
ETA is 3days.

**Comment by salazarsebas** [comment]
PR merged
